"""
CREATE A CLASS FOR ALL OUR DRAWING FUNCTIONALITIES

RESPONSIBILITIES:
DRAW DATABASE SETTINGS TABLE TO THE CONSOLE

DRAW TODOS_CSV FILE TO THE CONSOLE

DRAW IDENTICAL TABLE FOR TODOS FROM POSTGRESS DATABASE
"""
